### ISSUE TITLE
Node v4.x is not supported

### ISSUE THREAD

**Issue by urcadox** [CleverCloud/clever-tools#10]
Looks like I can't make `clever deploy` and `clever status` commands work in the 0.3.2 version.

Here is the error I get:

    ▶ clever deploy
    module.js:338
        throw err;
        ^   

    Error: Cannot find module '../build/Debug/nodegit.node'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:286:25)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/home/urcadox/.npm_install/lib/node_modules/clever-tools/node_modules/nodegit/lib/nodegit.js:16:12)
        at Module._compile (module.js:434:26)
        at Object.Module._extensions..js (module.js:452:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/home/urcadox/.npm_install/lib/node_modules/clever-tools/src/models/git.js:4:15)
        at Module._compile (module.js:434:26)
        at Object.Module._extensions..js (module.js:452:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)

I tried on my usual dev machine and on another on which I never installed clever-tools before.

**Comment by divarvel** [comment]
It looks like an issue with nodegit. What node version are you using?

**Comment by urcadox** [comment]
v4.1.1 (on both machines)

**Comment by divarvel** [comment]
nodegit 0.4 does not work on 4.x. Nodegit 0.5 does, but there are quite a few undocumented breaking changes. v4.x support is my current priority.

**Comment by FGRibreau** [comment]
> v4.x support is my current priority.

@divarvel great, I had the same issue :)

**Comment by Keruspe** [comment]
@divarvel I guess we can update the package.json and close this issue now, right?

**Comment by Keruspe** [comment]
fixed by f25e0f841aaded82a6798e66f8aa8c5b75c54d83
